# Generated by Django 5.2.2 on 2025-06-16 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default.jpg', help_text='Upload a profile picture (300x300 recommended)', upload_to='profile_pics'),
        ),
    ]
